create table role (
                      id int generated by default as identity primary key ,
                      role_name varchar not null
);

create table users (
                       id int generated by default as identity primary key ,
                       role_id int references role(id) not null,
                       first_name varchar(24) not null ,
                       last_name varchar(24) not null ,
                       password varchar(24) not null
);

create table event (
                       id int generated by default as identity primary key ,
                       event_name varchar(50) not null ,
                       description varchar(300) not null ,
                       planned_at timestamp not null ,
                       created_at timestamp default current_timestamp,
                       updated_at timestamp default current_timestamp
);

create table users_event (
                             user_id int references users(id) not null ,
                             event_id int references event(id) not null
);