create table roles
(
    id        int generated by default as identity primary key,
    role_name varchar not null
);

create table users
(
    id         int generated by default as identity primary key,
    first_name varchar(24) not null,
    last_name  varchar(24) not null,
    email      varchar(64) not null,
    password   varchar(64) not null
);

CREATE TABLE users_roles
(
    user_id bigint not null,
    role_id int    not null,
    primary key (user_id, role_id),
    foreign key (user_id) references users (id),
    foreign key (role_id) references roles (id)
);

create table events
(
    id          int generated by default as identity primary key,
    user_id     int          not null,
    event_name  varchar(50)  not null,
    description varchar(300) not null,
    planned_at  timestamp    not null,
    created_at  timestamp default current_timestamp,
    updated_at  timestamp default current_timestamp,
    foreign key (user_id) references users (id)
);

create table posts
(
    id          int generated by default as identity primary key,
    user_id     int         not null,
    title       varchar(36) not null,
    description varchar     not null,
    created_at  timestamp default current_timestamp,
    foreign key (user_id) references users (id)
);

create table users_events
(
    user_id  bigint not null,
    event_id int    not null,
    primary key (user_id, event_id),
    foreign key (user_id) references users (id),
    foreign key (event_id) references events (id)
);
